-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ACADEMIA_BD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ACADEMIA_BD` ;

-- -----------------------------------------------------
-- Schema ACADEMIA_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ACADEMIA_BD` DEFAULT CHARACTER SET utf8 ;
USE `ACADEMIA_BD` ;

-- -----------------------------------------------------
-- Table `ACADEMIA_BD`.`ALUMNO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ACADEMIA_BD`.`ALUMNO` ;

CREATE TABLE IF NOT EXISTS `ACADEMIA_BD`.`ALUMNO` (
  `DNI` VARCHAR(9) NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `APELLIDO` VARCHAR(45) NULL,
  `ID_ALUMNO` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID_ALUMNO`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ACADEMIA_BD`.`PROFESOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ACADEMIA_BD`.`PROFESOR` ;

CREATE TABLE IF NOT EXISTS `ACADEMIA_BD`.`PROFESOR` (
  `DNI` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `APELLIDO` VARCHAR(45) NULL,
  `ID_PROFESOR` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  PRIMARY KEY (`ID_PROFESOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ACADEMIA_BD`.`ASIGNATURA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ACADEMIA_BD`.`ASIGNATURA` ;

CREATE TABLE IF NOT EXISTS `ACADEMIA_BD`.`ASIGNATURA` (
  `COD_ASIGNATURA` VARCHAR(45) NOT NULL,
  `NOMBRE` VARCHAR(45) NULL,
  `NUM_CREDITOS` INT NOT NULL,
  PRIMARY KEY (`COD_ASIGNATURA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ACADEMIA_BD`.`MATRICULA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ACADEMIA_BD`.`MATRICULA` ;

CREATE TABLE IF NOT EXISTS `ACADEMIA_BD`.`MATRICULA` (
  `FK_ID_ALUMNO` INT NOT NULL,
  `FK_COD_ASIGNATURA` VARCHAR(45) NOT NULL,
  `NOTA` INT NULL,
  PRIMARY KEY (`FK_ID_ALUMNO`, `FK_COD_ASIGNATURA`),
  INDEX `fk_ALUMNO_has_ASIGNATURA_ASIGNATURA1_idx` (`FK_COD_ASIGNATURA` ASC) VISIBLE,
  INDEX `fk_ALUMNO_has_ASIGNATURA_ALUMNO1_idx` (`FK_ID_ALUMNO` ASC) VISIBLE,
  CONSTRAINT `fk_ALUMNO_has_ASIGNATURA_ALUMNO1`
    FOREIGN KEY (`FK_ID_ALUMNO`)
    REFERENCES `ACADEMIA_BD`.`ALUMNO` (`ID_ALUMNO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUMNO_has_ASIGNATURA_ASIGNATURA1`
    FOREIGN KEY (`FK_COD_ASIGNATURA`)
    REFERENCES `ACADEMIA_BD`.`ASIGNATURA` (`COD_ASIGNATURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ACADEMIA_BD`.`IMPARTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ACADEMIA_BD`.`IMPARTE` ;

CREATE TABLE IF NOT EXISTS `ACADEMIA_BD`.`IMPARTE` (
  `ASIGNATURA_COD_ASIGNATURA` VARCHAR(45) NOT NULL,
  `PROFESOR_ID_PROFESOR` INT NOT NULL,
  PRIMARY KEY (`ASIGNATURA_COD_ASIGNATURA`, `PROFESOR_ID_PROFESOR`),
  INDEX `fk_ASIGNATURA_has_PROFESOR_PROFESOR1_idx` (`PROFESOR_ID_PROFESOR` ASC) VISIBLE,
  INDEX `fk_ASIGNATURA_has_PROFESOR_ASIGNATURA1_idx` (`ASIGNATURA_COD_ASIGNATURA` ASC) VISIBLE,
  CONSTRAINT `fk_ASIGNATURA_has_PROFESOR_ASIGNATURA1`
    FOREIGN KEY (`ASIGNATURA_COD_ASIGNATURA`)
    REFERENCES `ACADEMIA_BD`.`ASIGNATURA` (`COD_ASIGNATURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASIGNATURA_has_PROFESOR_PROFESOR1`
    FOREIGN KEY (`PROFESOR_ID_PROFESOR`)
    REFERENCES `ACADEMIA_BD`.`PROFESOR` (`ID_PROFESOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
